### ISSUE TITLE
list presence keyword - bug

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1545]
When attempting to assign one specific list presence keyword to a chemical record, user sees a 'server error 500.'

Error does not appear when assigning other list presence keywords to the same chemical record.

List presence keyword user is attempting to assign is: "Cons electronics, mech appliances, and machinery" with slug = pucid_305 and dashboard_extractedlistpresencetag.id=474

error below:
```bash
[12/Jun/2020 19:25:41] [INFO] "GET /datadocument/320428/cards HTTP/1.0" 200 322520
[12/Jun/2020 19:25:47] [INFO] "GET /list_presence_tags_autocomplete/?q=cons HTTP/1.0" 200 386
[12/Jun/2020 19:25:54] [ERROR] Internal Server Error: /save_list_presence_tags/320428/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/dashboard/views/data_document.py", line 303, in save_list_presence_tag_form
    if tag_form.is_valid():
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 382, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "/app/dashboard/forms/tag_forms.py", line 42, in clean
    self.cleaned_data["tags"].remove(tag)
KeyError: 'tags'
[12/Jun/2020 19:25:54] [INFO] "POST /save_list_presence_tags/320428/ HTTP/1.0" 500 27
[12/Jun/2020 19:26:16] [INFO] "GET /login HTTP/1.0" 301 0
```

**Comment by kdionisio** [comment]
Bug was occurring because of a comma being used within the name of the tag. Once comma was removed from the tag name, there was no error message.  Would need to submit ticket to allow for use of comma in tag name if that were desired.
