### ISSUE TITLE
Search Down

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#1584]
**Describe the bug**
Search issues a 500

**To Reproduce**
1. Go to main page
2. Type water in search box
3. See error 500

**Expected behavior**
Should see search results
**Factotum Logs**
```bash
[20/Jul/2020 12:49:13] [WARNING] POST http://elasticsearch:9200/dashboard/_search [status:404 request:0.014s]
[20/Jul/2020 12:49:13] [ERROR] Internal Server Error: /search/product/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/dashboard/views/search.py", line 45, in search_model
    get_model_counts(request, decoded_q)
  File "/app/dashboard/views/search.py", line 72, in get_model_counts
    unique_counts[model] = get_unique_count(decoded_q, model)
  File "/app/elastic/search.py", line 341, in get_unique_count
    response = s.execute().to_dict()
  File "/usr/local/lib/python3.7/site-packages/elasticsearch_dsl/search.py", line 698, in execute
    **self._params
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 139, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 1484, in search
    body=body,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 352, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 256, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 288, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [dashboard]', dashboard, index_or_alias)
[20/Jul/2020 12:49:13] [INFO] "GET /search/product/?q=d2F0ZXI= HTTP/1.0" 500 27
[20/Jul/2020 12:49:15] [INFO] "GET /api/tasks/ HTTP/1.0" 200 81
[20/Jul/2020 12:49:19] [INFO] "GET / HTTP/1.0" 200 488909
[20/Jul/2020 12:49:20] [INFO] "GET /api/tasks/ HTTP/1.0" 200 81
```
Elastic Logs
```bash
{"type": "server", "timestamp": "2020-07-15T12:36:08,122+0000", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854",  "message": "[controller/127] [Main.cc@110] controller (64 bit): Version 7.3.1 (Build 1d93901e09ef43) Copyright (c) 2019 Elasticsearch BV"  }
{"type": "server", "timestamp": "2020-07-15T12:36:08,635+0000", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854",  "message": "using discovery type [single-node] and seed hosts providers [settings]"  }
{"type": "server", "timestamp": "2020-07-15T12:36:09,326+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854",  "message": "initialized"  }
{"type": "server", "timestamp": "2020-07-15T12:36:09,326+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854",  "message": "starting ..."  }
{"type": "server", "timestamp": "2020-07-15T12:36:09,709+0000", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854",  "message": "publish_address {172.21.0.3:9300}, bound_addresses {0.0.0.0:9300}"  }
{"type": "server", "timestamp": "2020-07-15T12:36:09,715+0000", "level": "INFO", "component": "o.e.b.BootstrapChecks", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854",  "message": "explicitly enforcing bootstrap checks"  }
{"type": "server", "timestamp": "2020-07-15T12:36:09,730+0000", "level": "INFO", "component": "o.e.c.c.Coordinator", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854",  "message": "cluster UUID [Ib9-0k6dQ_2_3H3h6LGDdg]"  }
{"type": "server", "timestamp": "2020-07-15T12:36:09,943+0000", "level": "INFO", "component": "o.e.c.s.MasterService", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854",  "message": "elected-as-master ([1] nodes joined)[{cb83e5c14854}{iigqbx8XRA2ViC5LE0dazA}{ty4TfPANTHq91OX-JbT2bg}{172.21.0.3}{172.21.0.3:9300}{dim}{ml.machine_memory=540973887488, xpack.installed=true, ml.max_open_jobs=20} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 6, version: 61, reason: master node changed {previous [], current [{cb83e5c14854}{iigqbx8XRA2ViC5LE0dazA}{ty4TfPANTHq91OX-JbT2bg}{172.21.0.3}{172.21.0.3:9300}{dim}{ml.machine_memory=540973887488, xpack.installed=true, ml.max_open_jobs=20}]}"  }
{"type": "server", "timestamp": "2020-07-15T12:36:09,983+0000", "level": "INFO", "component": "o.e.c.s.ClusterApplierService", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854",  "message": "master node changed {previous [], current [{cb83e5c14854}{iigqbx8XRA2ViC5LE0dazA}{ty4TfPANTHq91OX-JbT2bg}{172.21.0.3}{172.21.0.3:9300}{dim}{ml.machine_memory=540973887488, xpack.installed=true, ml.max_open_jobs=20}]}, term: 6, version: 61, reason: Publication{term=6, version=61}"  }
{"type": "server", "timestamp": "2020-07-15T12:36:10,018+0000", "level": "INFO", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854", "cluster.uuid": "Ib9-0k6dQ_2_3H3h6LGDdg", "node.id": "iigqbx8XRA2ViC5LE0dazA",  "message": "publish_address {172.21.0.3:9200}, bound_addresses {0.0.0.0:9200}"  }
{"type": "server", "timestamp": "2020-07-15T12:36:10,019+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854", "cluster.uuid": "Ib9-0k6dQ_2_3H3h6LGDdg", "node.id": "iigqbx8XRA2ViC5LE0dazA",  "message": "started"  }
{"type": "server", "timestamp": "2020-07-15T12:36:10,073+0000", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854", "cluster.uuid": "Ib9-0k6dQ_2_3H3h6LGDdg", "node.id": "iigqbx8XRA2ViC5LE0dazA",  "message": "license [67bf355a-1d80-45a9-8d40-c3d0b55e84e2] mode [basic] - valid"  }
{"type": "server", "timestamp": "2020-07-15T12:36:10,075+0000", "level": "INFO", "component": "o.e.g.GatewayService", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854", "cluster.uuid": "Ib9-0k6dQ_2_3H3h6LGDdg", "node.id": "iigqbx8XRA2ViC5LE0dazA",  "message": "recovered [1] indices into cluster_state"  }
{"type": "server", "timestamp": "2020-07-15T12:36:10,366+0000", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854", "cluster.uuid": "Ib9-0k6dQ_2_3H3h6LGDdg", "node.id": "iigqbx8XRA2ViC5LE0dazA",  "message": "Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[factotum_ws_logs][0]] ...])."  }
{"type": "server", "timestamp": "2020-07-15T12:36:33,819+0000", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854", "cluster.uuid": "Ib9-0k6dQ_2_3H3h6LGDdg", "node.id": "iigqbx8XRA2ViC5LE0dazA",  "message": "adding template [dashboard_template] for index patterns [dashboard]"  }
{"type": "server", "timestamp": "2020-07-15T12:40:51,858+0000", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854", "cluster.uuid": "Ib9-0k6dQ_2_3H3h6LGDdg", "node.id": "iigqbx8XRA2ViC5LE0dazA",  "message": "adding template [dashboard_template] for index patterns [dashboard]"  }
{"type": "deprecation", "timestamp": "2020-07-15T13:29:14,843+0000", "level": "WARN", "component": "o.e.d.a.b.BulkRequestParser", "cluster.name": "docker-cluster", "node.name": "cb83e5c14854", "cluster.uuid": "Ib9-0k6dQ_2_3H3h6LGDdg", "node.id": "iigqbx8XRA2ViC5LE0dazA",  "message": "[types removal] Specifying types in bulk requests is deprecated."  }
```
***Logstash Logs***
```bash
[2020-07-20T05:30:00,222][ERROR][logstash.inputs.jdbc     ] Java::JavaSql::SQLSyntaxErrorException: Unknown column 'puc.kind' in 'field list': SELECT
    id.rawchem_id as rawchem_id,
    NULLIF(rc.raw_cas, "") as rawchem_cas,
    NULLIF(rc.raw_chem_name, "") as rawchem_name,
    NULLIF(dss.sid, "") as truechem_dtxsid,
    NULLIF(dss.true_cas, "") as truechem_cas,
    NULLIF(dss.true_chemname, "") as truechem_name,
    id.datadocument_id as datadocument_id,
    NULLIF(gt.title, "") as datadocument_grouptype,
    NULLIF(dd.title, "") as datadocument_title,
    NULLIF(dd.subtitle, "") as datadocument_subtitle,
    id.product_id as product_id,
    NULLIF(p.upc, "") as product_upc,
    NULLIF(p.manufacturer, "") as product_manufacturer,
    NULLIF(p.brand_name, "") as product_brandname,
    NULLIF(p.title, "") as product_title,
    NULLIF(p.short_description, "") as product_shortdescription,
    NULLIF(p.long_description, "") as product_longdescription,
    id.puc_id as puc_id,
    NULLIF(puc.kind, "") as puc_kind,
    NULLIF(puc.gen_cat, "") as puc_gencat,
    NULLIF(puc.gen_cat, "") as puc_gencatfacet,
    NULLIF(puc.prod_fam, "") as puc_prodfam,
    NULLIF(puc.prod_type, "") as puc_prodtype,
    NULLIF(puc.description, "") as puc_description
FROM
    `logstash.id|id` id
    LEFT JOIN dashboard_rawchem rc ON id.rawchem_id = rc.id
    LEFT JOIN dashboard_datadocument dd ON id.datadocument_id = dd.id
    LEFT JOIN dashboard_product p ON id.product_id = p.id
    LEFT JOIN dashboard_puc puc ON id.puc_id = puc.id
    LEFT JOIN dashboard_dsstoxlookup dss ON rc.dsstox_id = dss.id
    LEFT JOIN dashboard_datagroup dg ON dd.data_group_id = dg.id
    LEFT JOIN dashboard_grouptype gt ON dg.group_type_id = gt.id

[2020-07-20T05:30:00,224][WARN ][logstash.inputs.jdbc     ] Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::JavaSql::SQLSyntaxErrorException: Unknown column 'puc.kind' in 'field list'>}
```

**Comment by mwfrost** [comment]
This issue was fixed in this PR:
https://github.com/HumanExposure/factotum_elastic/pull/32/files

Can we add a test to the `dashboard` suite that attempts to execute that SQL query against the database, so if another migration changes any of the fields, the test fails?

**Comment by dmlyons2** [comment]
Did not update dev to master on factotum_elastic last sprint. Applied to prod and waiting for next logstash event
