### ISSUE TITLE
Search gives Server Error (500)

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#1691]
**Describe the bug**
Search gives a server error (500)

**To Reproduce**
1. Go to navbar search box
2. Enter 'water' in the search box and return
3. See error

**Expected behavior**
Should give search results

**Note**
Waited overnight for rebuild of indexes as well as issued a `python manage.py search_index --rebuild` there appears to be no dashboard_index in Elasticsearch.

**Logs**
```bash
[14/Nov/2020 13:11:35] [ERROR] Internal Server Error: /search/product/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/dashboard/views/search.py", line 42, in search_model
    get_model_counts(request, decoded_q)
  File "/app/dashboard/views/search.py", line 69, in get_model_counts
    unique_counts[model] = get_unique_count(decoded_q, model)
  File "/app/elastic/search.py", line 351, in get_unique_count
    response = s.execute().to_dict()
  File "/usr/local/lib/python3.7/site-packages/elasticsearch_dsl/search.py", line 715, in execute
    self, es.search(index=self._index, body=self.to_dict(), **self._params)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 1663, in search
    body=body,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 313, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [dashboard]', dashboard, index_or_alias)
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Agency version

**Comment by dmlyons2** [comment]
Logstash Log
```bash
[2020-11-17T06:30:00,097][ERROR][logstash.inputs.jdbc     ] Java::JavaSql::SQLSyntaxErrorException: Table 'prod_factotum.logstash.id|id' doesn't exist: SELECT
    id.rawchem_id as rawchem_id,
    NULLIF(rc.raw_cas, "") as rawchem_cas,
    NULLIF(rc.raw_chem_name, "") as rawchem_name,
    NULLIF(dss.sid, "") as truechem_dtxsid,
    NULLIF(dss.true_cas, "") as truechem_cas,
    NULLIF(dss.true_chemname, "") as truechem_name,
    id.datadocument_id as datadocument_id,
    NULLIF(gt.title, "") as datadocument_grouptype,
    NULLIF(dd.title, "") as datadocument_title,
    NULLIF(dd.subtitle, "") as datadocument_subtitle,
    id.product_id as product_id,
    NULLIF(p.upc, "") as product_upc,
    NULLIF(p.manufacturer, "") as product_manufacturer,
    NULLIF(p.brand_name, "") as product_brandname,
    NULLIF(p.title, "") as product_title,
    NULLIF(p.short_description, "") as product_shortdescription,
    NULLIF(p.long_description, "") as product_longdescription,
    id.puc_id as puc_id,
    NULLIF(puckind.code, "") as puc_kind,
    NULLIF(puc.gen_cat, "") as puc_gencat,
    NULLIF(puc.gen_cat, "") as puc_gencatfacet,
    NULLIF(puc.prod_fam, "") as puc_prodfam,
    NULLIF(puc.prod_type, "") as puc_prodtype,
    NULLIF(puc.description, "") as puc_description
FROM
    `logstash.id|id` id
    LEFT JOIN dashboard_rawchem rc ON id.rawchem_id = rc.id
    LEFT JOIN dashboard_datadocument dd ON id.datadocument_id = dd.id
    LEFT JOIN dashboard_product p ON id.product_id = p.id
    LEFT JOIN dashboard_puc puc ON id.puc_id = puc.id
    LEFT JOIN dashboard_puckind puckind on puc.kind_id = puckind.id
    LEFT JOIN dashboard_dsstoxlookup dss ON rc.dsstox_id = dss.id
    LEFT JOIN dashboard_datagroup dg ON dd.data_group_id = dg.id
    LEFT JOIN dashboard_grouptype gt ON dg.group_type_id = gt.id

[2020-11-17T06:30:00,098][WARN ][logstash.inputs.jdbc     ] Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::JavaSql::SQLSyntaxErrorException: Table 'prod_factotum.logstash.id|id' doesn't exist>}
```

**Comment by dmlyons2** [comment]
Python manage.py showmigrations
```bash
/app # python manage.py showmigrations
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
authtoken
 [X] 0001_initial
 [X] 0002_auto_20160226_1747
celery_usertask
 [X] 0001_initial
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
dashboard
 [X] 0001_squashed_migrations_0001_to_0158 (164 squashed migrations)
 [X] 0159_hp_pucs_blank_attribute
 [X] 0160_doc_epa_reg_number
 [X] 0161_product_epa_reg_number
 [X] 0162_created_by_updated_by
 [X] 0163_puc_kind_choices
 [X] 0164_funcuse_extraction_script
 [X] 0165_extractedhp_options_and_extractedhpdoc
 [X] 0166_allow_blank_extr_scr
 [X] 0167_puckind
 [X] 0168_detected_chem_flag
 [X] 0169_rename_extracted_chemical
 [X] 0170_product_fields_verbose_name
 [X] 0171_product_uber_puc_view
 [X] 0172_make_uberpuc_model
 [X] 0173_lm_study_type
elastic
 [X] 0001_logstash_views
 [X] 0002_upd_logstash_views
 [X] 0003_fix_puc_in_view
 [X] 0004_querylog
feedback
 [X] 0001_initial
 [X] 0002_comment_email
sessions
 [X] 0001_initial
taggit
 [X] 0001_initial
 [X] 0002_auto_20150616_2121
```

**Comment by dmlyons2** [comment]
There was a failure to create the view. View created and all is good.
