### ISSUE TITLE
Error when uploading LM Extracted Text by Script

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2145]
I tried to upload a test file with extracted text by script to a LM datagroup. But I received an error, and was not able to upload the file. See the error text below.

This is the data group and the test csv file is attached.
https://ccte-factotum-stg.epa.gov/datagroup/890/?task_id=372f5974-e82f-44fd-924a-b53369bb07a5

[test upload 3M.csv](https://github.com/HumanExposure/factotum/files/7737992/test.upload.3M.csv)

It looks like the upload is looking for a field 'cleaning_qa_checked', which is not in the upload template. It might have been added when creating the composition cleaning QA? But there is no data cleaning QA relevant to the LM datatype, so it shouldn't be a required column.  There is already a 'qa_flag' and 'qa_who' column in the template. 

Definition of Done:
The LM script upload works as stated on the template, and does not require a 'cleaning_qa_checked' column. 

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1048, "Column 'cleaning_qa_checked' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/celery_usertask/tasks.py", line 52, in _inner
    return func(self, *args, **kwargs)
  File "/app/celery_filetask/tasks.py", line 27, in _inner
    return func(self, *inputs[0], **inputs[1])
  File "/app/celery_formtask/tasks.py", line 32, in processform
    return form.save()
  File "/app/dashboard/forms/data_group.py", line 705, in save
    chems = inheritance_bulk_create(created_objs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/app/dashboard/utils.py", line 469, in inheritance_bulk_create
    cursor.execute(sql_str, sql_values)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/cacheops/transaction.py", line 93, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django_mysql/monkey_patches.py", line 30, in execute
    return orig_execute(self, sql, args)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    raise utils.IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'cleaning_qa_checked' cannot be null")

**Comment by mwfrost** [comment]
This version of the csv file has been modified to use document ID 9, which is an LM document in the development scratch database. It has also had the "LOD" and "LOQ" values moved into the "statistical_values" column as per ticket #2141 
[test_dev.upload.3M.csv](https://github.com/HumanExposure/factotum/files/7763332/test_dev.upload.3M.csv)
