### ISSUE TITLE
 Update Testing Strategy Document

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2178]
Go through testing suite and update documentation

**Comment by mwfrost** [comment]
For discussion:
```
(factotum) PS C:\bit9prog\dev\factotum> python manage.py test dashboard.tests.functional
Creating test database for alias 'default'...
System check identified no issues (1 silenced).
.................................................................................................................................................FFF...F..................................................................FFFFFFFFFFFF....................................E.......E.......................E....Restoring 5 unacknowledged 
message(s)
.......E......
======================================================================
ERROR: test_audit_log_presence_upload (dashboard.tests.functional.test_auditlog.AuditLogTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_auditlog.py", line 245, in test_audit_log_presence_upload
    in_mem_sample_csv = make_upload_csv("sample_files/presence_good.csv")
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_auditlog.py", line 31, in make_upload_csv
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sample_files/presence_good.csv'

======================================================================
ERROR: test_delete (dashboard.tests.functional.test_datadocument_detail.DataDocumentDetailTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_datadocument_detail.py", line 277, in test_delete
    "sample_files/images/datadocuments/document_sample_file.pdf", "rb"
FileNotFoundError: [Errno 2] No such file or directory: 'sample_files/images/datadocuments/document_sample_file.pdf'

======================================================================
ERROR: test_chemical_presence_upload (dashboard.tests.functional.test_extracted_text_upload.UploadExtractedFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_extracted_text_upload.py", line 284, in test_chemical_presence_upload
    in_mem_sample_csv = make_upload_csv("sample_files/presence_cpcat.csv")
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_extracted_text_upload.py", line 32, in make_upload_csv
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sample_files/presence_cpcat.csv'

======================================================================
ERROR: test_image_upload (dashboard.tests.functional.test_product_detail.TestProductDetail)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_product_detail.py", line 226, in test_image_upload
    "rb",
FileNotFoundError: [Errno 2] No such file or directory: 'sample_files/images/products/product_image_upload_valid/dave_or_grant.png'

======================================================================
FAIL: test_image_directory_exceeds_count_error (dashboard.tests.functional.test_product_csv_upload.UploadProductTest)
Rows with images that arent in the uploaded directory should be rejected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_product_csv_upload.py", line 291, in test_image_directory_exceeds_count_error
    % env.PRODUCT_IMAGE_DIRECTORY_MAX_FILE_COUNT,
  File "C:\bit9prog\dev\anaconda\envs\factotum\lib\site-packages\django\test\testcases.py", line 454, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'The image directory has too many files.  Please reduce the number of document upload at one time to &lt; 500.' in 
response

======================================================================
FAIL: test_image_directory_too_large_error (dashboard.tests.functional.test_product_csv_upload.UploadProductTest)
Rows with images that arent in the uploaded directory should be rejected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_product_csv_upload.py", line 267, in test_image_directory_too_large_error
    % (env.PRODUCT_IMAGE_DIRECTORY_MAX_UPLOAD / 1000000),
  File "C:\bit9prog\dev\anaconda\envs\factotum\lib\site-packages\django\test\testcases.py", line 454, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'The image directory is too large.  Please reduce the size of the directory to &lt; 5 MB' in response

======================================================================
FAIL: test_image_file_too_large_error (dashboard.tests.functional.test_product_csv_upload.UploadProductTest)
Rows with images that arent in the uploaded directory should be rejected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_product_csv_upload.py", line 243, in test_image_file_too_large_error
    "The error message could not be found in the text",
AssertionError: None is not true : The error message could not be found in the text

======================================================================
FAIL: test_valid_product_data_upload_with_image (dashboard.tests.functional.test_product_csv_upload.UploadProductTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_product_csv_upload.py", line 147, in test_valid_product_data_upload_with_image
    self.assertContains(resp, "5 records have been successfully uploaded.")
  File "C:\bit9prog\dev\anaconda\envs\factotum\lib\site-packages\django\test\testcases.py", line 454, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find '5 records have been successfully uploaded.' in response

======================================================================
FAIL: test_failure_blank_form (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 165, in test_failure_blank_form
    "raw_category": ["This field is required."],
AssertionError: {'puc[112 chars]ed.'], 'created_by_id': ['This field is requir[96 chars]d.']} != {'puc[112 chars]ed.']}
- {'created_at': ['This field is required.'],
-  'created_by_id': ['This field is required.'],
-  'datagroup': ['This field is required.'],
? ^

+ {'datagroup': ['This field is required.'],
? ^

   'puc': ['This field is required.'],
-  'puc_assigned_usr_id': ['This field is required.'],
   'raw_category': ['This field is required.']}

======================================================================
FAIL: test_failure_incorrect_ids (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 186, in test_failure_incorrect_ids
    "Select a valid choice. "
AssertionError: {'puc[256 chars]es.'], 'created_by_id': ['This field is requir[96 chars]d.']} != {'puc[256 chars]es.']}
Diff is 1043 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_failure_no_products (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 203, in test_failure_no_products
    form.errors, {"datagroup": ["No Products will be affected."]}
AssertionError: {'created_by_id': ['This field is required.[93 chars]d.']} != {'datagroup': ['No Products will be affected.']}
+ {'datagroup': ['No Products will be affected.']}
- {'created_at': ['This field is required.'],
-  'created_by_id': ['This field is required.'],
-  'puc_assigned_usr_id': ['This field is required.']}

======================================================================
FAIL: test_failure_rawcategory_datagroup_mismatch (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 226, in test_failure_rawcategory_datagroup_mismatch
    "No Documents with that Raw Category in the provided Data Group."
AssertionError: {'created_by_id': ['This field is required.[93 chars]d.']} != {'raw_category': ['No Documents with that R[37 chars]p.']}
+ {'raw_category': ['No Documents with that Raw Category in the provided Data '
+                   'Group.']}
- {'created_at': ['This field is required.'],
-  'created_by_id': ['This field is required.'],
-  'puc_assigned_usr_id': ['This field is required.']}

======================================================================
FAIL: test_successful_document_with_multiple_products (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 112, in test_successful_document_with_multiple_products
    self.assertTrue(form.is_valid())
AssertionError: False is not true

======================================================================
FAIL: test_successful_form (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
Test form can be validated and saved with valid data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 50, in test_successful_form
    self.assertTrue(form.is_valid())
AssertionError: False is not true

======================================================================
FAIL: test_successful_form_duplicate_request (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
New form submissions should override previous submissions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 71, in test_successful_form_duplicate_request
    self.assertTrue(form.is_valid())
AssertionError: False is not true

======================================================================
FAIL: test_successful_form_reassign_puc (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 94, in test_successful_form_reassign_puc
    self.assertTrue(form.is_valid())
AssertionError: False is not true

======================================================================
FAIL: test_successful_resubmit_new_product (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 141, in test_successful_resubmit_new_product
    self.assertTrue(form.is_valid())
AssertionError: False is not true

======================================================================
FAIL: test_successful_single_product_attached_to_different_documents (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 128, in test_successful_single_product_attached_to_different_documents
    self.assertTrue(form.is_valid())
AssertionError: False is not true

======================================================================
FAIL: test_successful_update_uber_puc (dashboard.tests.functional.test_rawcategory_to_puc_form.TestRawCategoryToPUCForm)
Confirm that a previous "AU" assignment is overridden
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_form.py", line 255, in test_successful_update_uber_puc
    self.assertTrue(form.is_valid())
AssertionError: False is not true

======================================================================
FAIL: test_list_documents_without_products_are_not_counted (dashboard.tests.functional.test_rawcategory_to_puc_view.TestRawCategoryToPUCView)
Add a document without a product.  Verify it's not counted
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bit9prog\dev\factotum\dashboard\tests\functional\test_rawcategory_to_puc_view.py", line 138, in test_list_documents_without_products_are_not_counted      
    response.context["object_list"][0],
AssertionError: {'dat[48 chars]id': 1, 'raw_category': 'visible', 'batch_puc_[52 chars]': 5} != {'dat[48 chars]id': 237, 'raw_category': 'visible', 'batch_pu[54 chars]': 5}
  {'batch_puc_id': None,
   'batch_puc_str': ' -  - ',
-  'data_group__id': 1,
?                    ^

+  'data_group__id': 237,
?                    ^^^

   'data_group__name': 'Test Data Group',
   'product_count': 5,
   'raw_category': 'visible'}

----------------------------------------------------------------------
Ran 317 tests in 2718.767s

FAILED (failures=16, errors=4)
Destroying test database for alias 'default'...
```
